### ISSUE TITLE
Some defaults are not printed in the table

### ISSUE THREAD

**Issue by ainquel** [Frefreak/mdantic#1]
Hello, I've noticed this bug while playing with this lib, it doesn't render default variables == 0, None, [], {}, False

it is related to this line https://github.com/Frefreak/mdantic/blob/master/mdantic.py#L79
```python
default = str(f.default or "")
```
with a little adjustment it works fine,

```python
default = str(f.default if f.default is not None else "")
```

**Comment by Frefreak** [comment]
Thanks!
