### ISSUE TITLE
Markdown extension error

### ISSUE THREAD

**Issue by curtisma** [Frefreak/mdantic#2]
Is anyone actively using this extension?

I just tried it with the latest version of mkdocs and I get the following error when I run "mkdocs serve"

```bash
INFO     -  Building documentation...
ERROR    -  Config value: 'markdown_extensions'. Error: Failed loading extension "markdown-mdantic".
Aborted with 1 Configuration Errors!
```

I have the following in my mkdocs.yml file:
```yaml
markdown_extensions:
  - mkdocs-click
  - markdown-mdantic
```

The following version is more similar to the version in the readme, but has the same error.
```yaml
markdown_extensions:
  - mkdocs-click
  - markdown_mdantic
```

**Comment by Frefreak** [comment]
Personally I haven't used this recently and I'm not sure if there's anyone using it right now, but I will investigate this issue to make it works "again".

**Comment by Frefreak** [comment]
Now it seems we should use "mdantic" as the import name (I have addressed this in README), could you please try with that name?

BTW the old code should work after the config change, but I have made a few cleanup (deprecation api, etc) so you can also try the newest version.

**Comment by curtisma** [comment]
@Frefreak, Thanks for the update!  I'm excited to try this out.

> Now it seems we should use "mdantic" as the import name (I have addressed this in README), could you please try with that name?

Yeah, I'll try it today.

> BTW the old code should work after the config change, but I have made a few cleanup (deprecation api, etc) so you can also try the newest version.

I assume you mean v1.3.3 is the new version from yesterday and v1.3.1 is the old version from August 2020.  If so, yeah, I'll update it before I try it.

![image](https://user-images.githubusercontent.com/4685385/197517692-d6388a00-1e12-4191-90fc-3dd997b88ee9.png)

**Comment by Frefreak** [comment]
Closing for now. Feel free to reopen if there further question.
