### ISSUE TITLE
'FieldInfo' object has no attribute 'type_'

### ISSUE THREAD

**Issue by trevorWieland** [Frefreak/mdantic#4]
I think this might be introduced by pydantic >= 2.0, but FieldInfo objects no longer have a 'type_' attribute in favor of .annotation, as well as default working a bit differently now. 

Related, mdantic is using __fields__ which is deprecated in favor of model_fields. 

Messing around abit with it on my own, I have a local version working for my own needs, but since there aren't really any test cases to validate that my changes are keeping expected behavior I'm a bit hesitant to open a PR yet...

If you're still maintaining this library I'd be willing to help out and add test cases / push my changes / etc if you'd like, but otherwise I might just spin up my own version if that's alright

**Comment by Frefreak** [comment]
Thanks for you interest in this project. I do still maintain this library so feel free to open a PR.

**Comment by trevorWieland** [comment]
Got it, I'll work on putting together my changes into a PR in that case. Is there anything you would like to see in terms of test cases? I imagine that some of my changes might be breaking changes for older versions of pydantic.

**Comment by Frefreak** [comment]
For the test cases I feel like a simple model with some variant of types is enough to both act as a demo and a sanity check. You can add others if you like.

For the breaking changes I think we should follow the new `pydantic` v2 version. We can only support `>= 2.0` if necessary.

**Comment by trevorWieland** [comment]
#5 is up for review

**Comment by Frefreak** [comment]
pypi version also updated to **2.1.0**, closing
